export const GLOBAL_GUARDRAILS = [
  "Preserve the exact room layout and camera perspective.",
  "Do not remodel, repaint, change finishes, or alter architecture in any way.",
  "Do not add, remove, or change windows, doors, built-ins, plumbing, or electrical fixtures.",
  "Do not place any furniture in front of doors or within the door swing area—keep every doorway fully clear and usable.",
  "Maintain an unobstructed path from the main entry or camera position through the room; do not place chairs in that path.",
  "Prefer minimal staging with appropriately scaled pieces; do not fill every empty space, and only add accent chairs when ample room remains without impacting circulation or door clearance.",
  "Keep at least 36 inches of clear walking path everywhere people would naturally walk; never block doors, halls, windows, vents, or switches.",
  "HARD RULES (MUST FOLLOW):",
  "NEVER place ANY furniture within 4 feet (1.2m) of ANY door, doorway, or door swing area.",
  "Keep ALL doorways fully clear and visible; if unsure, leave the area empty.",
  "If a placement might obstruct a doorway or circulation, OMIT the furniture (do not try to fill space).",
  "WINDOW RULES (MUST FOLLOW):",
  "NEVER place wall art, mirrors, shelves, or any objects over/inside the window opening (no frames hanging on windows).",
  "Keep windows visible and unobstructed; do not cover the glass with furniture, art, or decor.",
  "Window treatments are allowed (simple neutral curtains or blinds), but they must look realistic and not block the window opening entirely.",
  "COMPOSITION RULES (MUST FOLLOW):",
  "Do NOT try to center furniture for the camera or make the scene symmetrical.",
  "Place furniture where it realistically fits given doors, windows, and circulation—even if it looks off-center in the photo.",
  "Natural asymmetry is acceptable; prioritize function and clear paths over visual centering.",
] as const;

export const ROOM_SPECIFIC_GUARDRAILS: Record<string, readonly string[]> =
  {
    bathroom: [
      "Do not change or add fixtures—keep existing lighting, plumbing, and hardware exactly as-is.",
      "Never place anything inside the tub or shower; leave all wet zones completely empty.",
      "Countertop styling must stay minimal: create only one small clustered vignette and keep the sink/faucet zone mostly clear.",
      "Flooring: at most one small bath mat outside wet zones; never add rugs, runners, or overlapping mats.",
      "Keep every toilet, vanity, tub/shower, door, and window fully clear and unobstructed.",
    ],
    entry: [
      "Keep the main door, sidelight, stairs, and walk paths completely clear—omit furniture if it risks blocking egress.",
      "Never place furniture within door swings or the first 3–4 feet of any stair landing; preserve sight lines to steps.",
      "Prioritize minimal decor; avoid clutter, bulky items, or anything that narrows the walkway.",
      "If uncertain about clearance, default to leaving the entry empty.",
    ],
    bedroom: [
      "Keep bed placement realistic and do not block closet doors.",
      "Add nightstands or lamps only if space allows, and do not add extra ceiling fixtures.",
      "If the room is small or wall space is limited, use a FULL or TWIN bed (not queen/king).",
      "If a standard bed would block a window, stage as a GUEST ROOM / OFFICE flex room (daybed or twin + small desk) and keep windows fully visible.",
      "Avoid benches at the foot of the bed in small rooms; prioritize circulation.",
      "If adding curtains/blinds, use light neutral tones and keep them outside the glass area (mounted above/around the window), never as a substitute for wall art.",
      "If the bed must be placed on the same wall as a window due to room constraints, center the bed under the window and keep it aligned with the window trim.",
    ],
    "living room": [
      "Follow the STRICT FURNITURE SET block exactly—never exceed the allowed items or counts.",
      "Prefer placing the sofa or sectional against the longest uninterrupted wall that is NOT near doors/entry.",
      "Only add an accent chair when the STRICT block explicitly allows it and the placement leaves generous door and pathway clearance.",
      "Place the primary sofa or loveseat flush against the main wall when feasible—prefer the longest uninterrupted wall, avoid floating furniture, and keep every doorway, window, vent, and circulation path clear.",
    ],
    kitchen: [
      "Keep countertops mostly visible; only add the minimal optional decor described in the STRICT block.",
      "Never block appliances, cabinet doors, drawers, or their clearances—you must leave room to open everything fully.",
      "Floor coverings: ONLY one small mat directly in front of the sink is allowed; no other rugs or runners.",
      "Open shelving is optional only when a clearly empty wall segment between upper cabinets exists and is not a window; never create shelving on windows.",
    ],
    "dining room": [
      "Stage exactly ONE dining table; do not add multiple tables, credenzas, or makeshift islands.",
      "Keep chair counts conservative (2–4 chairs for standard rooms, 6–8 only when clearly large) and leave sides open if space is tight.",
      "Tabletop styling must stay minimal: one simple centerpiece plus at most one runner OR one set of placemats—never full place settings.",
      "Never block any doors, windows, or walk paths; leave chair pull-out clearance obvious and remove pieces if uncertain.",
      "Only add a rug when the dining area is clearly large and the rug fits fully beneath the table and chairs without cutting off circulation paths.",
    ],
    office: [
      "Stage exactly ONE desk plus ONE office chair—never add additional desks or seating clusters.",
      "Keep accessories modern and minimal; at most one rug and one subtle desk accessory per the STRICT block.",
      "Never block doors, door swings, windows, vents, or the main walk path; if uncertain, remove optional items.",
      "Forbidden categories: beds, sofas/sectionals, dining furniture, kitchen pieces, bulky storage like filing cabinets or large hutches.",
    ],
    "outdoor space": [
      "Keep all doors, gates, walk paths, and steps completely clear; omit furniture if there is any doubt.",
      "Use outdoor-rated furniture only; if a piece might read as indoor furniture, leave it out.",
      "Default to minimal staging; if uncertain whether furniture fits, omit it entirely.",
      "Maintain generous safety clearance around grills, fire pits, or outdoor heaters—never place seating near heat sources.",
    ],
  } as const;
