CREATE TABLE IF NOT EXISTS feedback_submissions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz DEFAULT now(),
    user_id integer REFERENCES users(id),
    email text,
    source text NOT NULL DEFAULT 'nav_tab',
    goal text NOT NULL,
    rating integer NOT NULL,
    issue text,
    requested_feature text,
    persona text,
    usage_frequency text,
    pricing_preference text,
    willingness_to_pay_range text,
    watermark_preference text,
    watermark_text_preference text,
    freeform_feedback text,
    can_publish_testimonial boolean NOT NULL DEFAULT false,
    testimonial_name text,
    testimonial_company text,
    can_share_before_after boolean NOT NULL DEFAULT false,
    job_id text,
    plan_type text,
    room_type text,
    style_selected text,
    device_type text,
    country text
);
