export const COMPONENT_ERRORS = ["COMPONENT_NOT_REGISTERED", "COMPONENT_TASK_MISMATCH", "COMPONENT_DEPENDENCY_MISSING", "COMPONENT_DEPENDENCY_INVALID", "COMPONENT_OUTPUT_INVALID", "COMPONENT_ARTIFACT_INVALID", "COMPONENT_LICENSE_BLOCKED", "COMPONENT_TIMEOUT", "COMPONENT_CANCELLED", "COMPONENT_RESOURCE_LIMIT", "COMPONENT_EXECUTION_FAILED", "COMPONENT_NETWORK_FORBIDDEN"] as const;
export type ComponentErrorCode = typeof COMPONENT_ERRORS[number];
export type SceneInputErrorCode = ComponentErrorCode | "INVALID_IMAGE" | "UNSUPPORTED_IMAGE" | "UNSUPPORTED_TRANSPARENCY" | "IMAGE_TOO_LARGE" | "INVALID_SELECTION" | "SELECTION_ALIGNMENT_UNKNOWN" | "INVALID_TRANSFORM" | "ARTIFACT_HASH_MISMATCH" | "ARTIFACT_SIZE_MISMATCH" | "ARTIFACT_INVALID" | "ARTIFACT_ALREADY_PUBLISHED" | "ARTIFACT_PATH_VIOLATION" | "ARTIFACT_CONFLICT" | "ARTIFACT_MISSING" | "ARTIFACT_BUSY" | "ARTIFACT_LIMIT" | "ARTIFACT_IO";
/** Bounded public diagnostics; never attach native errors, paths or image metadata. */
export class SceneInputError extends Error {
    constructor(readonly code: SceneInputErrorCode) { super(code); this.name = "SceneInputError"; }
}
export function reject(code: SceneInputErrorCode): never { throw new SceneInputError(code); }
